In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\tom_r\Downloads\Crimes_-_2001_to_Present_20250402.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8285876 entries, 0 to 8285875
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.3+ GB

In [4]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,07/29/2022 03:39:00 AM,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,25.0,30.0,17,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,01/03/2023 04:44:00 PM,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,28.0,26.0,18,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
3,13203321,JG415333,09/06/2023 05:00:00 PM,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,42.0,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
4,13204489,JG416325,09/06/2023 11:00:00 AM,0000X E 8TH ST,0810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,4.0,32.0,06,1176857.0,1896680.0,2023,11/04/2023 03:40:18 PM,41.871835,-87.626151,"(41.871834768, -87.62615082)"

In [5]:
df['Primary Type'].value_counts()

Primary Type
THEFT                                1756378
BATTERY                              1509789
CRIMINAL DAMAGE                       942492
NARCOTICS                             759790
ASSAULT                               551492
OTHER OFFENSE                         515930
BURGLARY                              439744
MOTOR VEHICLE THEFT                   420993
DECEPTIVE PRACTICE                    378865
ROBBERY                               311142
CRIMINAL TRESPASS                     223692
WEAPONS VIOLATION                     121649
PROSTITUTION                           70301
OFFENSE INVOLVING CHILDREN             59394
PUBLIC PEACE VIOLATION                 54144
SEX OFFENSE                            33393
CRIM SEXUAL ASSAULT                    27352
INTERFERENCE WITH PUBLIC OFFICER       19695
LIQUOR LAW VIOLATION                   15275
GAMBLING                               14653
ARSON                                  14195
HOMICIDE                               13718
CRIMINAL SEXUAL ASSAULT                10355
KIDNAPPING                              7445
STALKING                                5803
INTIMIDATION                            5017
CONCEALED CARRY LICENSE VIOLATION       1498
OBSCENITY                                921
PUBLIC INDECENCY                         214
NON-CRIMINAL                             189
OTHER NARCOTIC VIOLATION                 157
HUMAN TRAFFICKING                        129
NON - CRIMINAL                            38
RITUALISM                                 24
NON-CRIMINAL (SUBJECT SPECIFIED)           9
DOMESTIC VIOLENCE                          1
Name: count, dtype: int64

In [6]:
df['Description'].value_counts()

Description
SIMPLE                                               972695
$500 AND UNDER                                       667349
DOMESTIC BATTERY SIMPLE                              647304
TO VEHICLE                                           463861
OVER $500                                            450662
                                                      ...
KEEP PLACE OF JUV PROSTITUTION                            1
THEFT RETAIL                                              1
FINANCIAL IDENTITY THEFT: $300 & UNDER                    1
AGGRAVATED: HANDS / FIST / FEET NO / MINOR INJURY         1
KEEPING PLACE OF PROSTITUTION                             1
Name: count, Length: 573, dtype: int64

In [7]:
# make column names sql friendly
df.columns = [col.lower().replace(" ", "_") for col in df.columns]

In [8]:
df.columns.values

array(['id', 'case_number', 'date', 'block', 'iucr', 'primary_type',
       'description', 'location_description', 'arrest', 'domestic',
       'beat', 'district', 'ward', 'community_area', 'fbi_code',
       'x_coordinate', 'y_coordinate', 'year', 'updated_on', 'latitude',
       'longitude', 'location'], dtype=object)

In [9]:
# convert date columns
df['date'] = pd.to_datetime(df['date'])

In [10]:
df.head()

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,13311263,JG503434,2022-07-29 03:39:00,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,25.0,30.0,17,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,2023-01-03 16:44:00,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,28.0,26.0,18,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,11227634,JB147599,2017-08-26 10:00:00,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
3,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,42.0,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
4,13204489,JG416325,2023-09-06 11:00:00,0000X E 8TH ST,0810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,4.0,32.0,06,1176857.0,1896680.0,2023,11/04/2023 03:40:18 PM,41.871835,-87.626151,"(41.871834768, -87.62615082)"

In [11]:
df['beat']

0          1033
1          1122
2           122
3           122
4           123
           ...
8285871    1424
8285872     132
8285873    2535
8285874    1925
8285875    1223
Name: beat, Length: 8285876, dtype: int64

In [13]:
# strip unwanted column

wanted_columns = ['id', 'case_number', 'date', 'block', 'primary_type',
       'description', 'location_description', 'arrest', 'domestic',
       'beat', 'district', 'ward', 'community_area', 
       'x_coordinate', 'y_coordinate', 'year', 'updated_on', 'latitude',
       'longitude', 'location']

df = df[wanted_columns].copy()

In [14]:
df

,id,case_number,date,block,primary_type,description,location_description,arrest,domestic,beat,district,ward,community_area,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,13311263,JG503434,2022-07-29 03:39:00,023XX S TROY ST,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,1033,10.0,25.0,30.0,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,2023-01-03 16:44:00,039XX W WASHINGTON BLVD,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,1122,11.0,28.0,26.0,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,11227634,JB147599,2017-08-26 10:00:00,001XX W RANDOLPH ST,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,122,1.0,42.0,32.0,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
3,13203321,JG415333,2023-09-06 17:00:00,002XX N Wells st,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,122,1.0,42.0,32.0,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
4,13204489,JG416325,2023-09-06 11:00:00,0000X E 8TH ST,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,123,1.0,4.0,32.0,1176857.0,1896680.0,2023,11/04/2023 03:40:18 PM,41.871835,-87.626151,"(41.871834768, -87.62615082)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8285871,13786420,JJ194332,2025-03-24 18:45:00,015XX N MILWAUKEE AVE,THEFT,RETAIL THEFT,SMALL RETAIL STORE,False,False,1424,14.0,1.0,24.0,1163050.0,1910381.0,2025,04/01/2025 03:41:49 PM,41.909732,-87.676457,"(41.909732366, -87.676456656)"
8285872,13785709,JJ194066,2025-03-24 04:30:00,003XX E 21ST ST,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,132,1.0,3.0,33.0,1178551.0,1890317.0,2025,04/01/2025 03:41:49 PM,41.854336,-87.620126,"(41.854335843, -87.620125605)"
8285873,13790202,JJ199106,2025-03-22 10:15:00,036XX W WABANSIA AVE,THEFT,FROM BUILDING,APARTMENT,False,False,2535,25.0,26.0,23.0,1151634.0,1911049.0,2025,04/01/2025 03:40:58 PM,41.911798,-87.718377,"(41.911797668, -87.71837683)"
8285874,13785321,JJ193561,2025-03-24 17:34:00,006XX W ROSCOE ST,CRIMINAL TRESPASS,TO RESIDENCE,APARTMENT,False,False,1925,19.0,44.0,6.0,1171253.0,1922813.0,2025,04/01/2025 03:41:49 PM,41.943670,-87.645956,"(41.943670005, -87.645956354)"
8285875,13784967,JJ192918,2025-03-24 09:45:00,023XX W MADISON ST,THEFT,RETAIL THEFT,GROCERY FOOD STORE,True,False,1223,12.0,27.0,28.0,1160808.0,1899960.0,2025,04/01/2025 03:41:49 PM,41.881183,-87.684982,"(41.881183104, -87.68498211)"